# TCL File Generated by Component Editor 11.0
# Tue Jul 19 13:15:52 PDT 2011


# +-----------------------------------
# | 
# | reset_and_status "ACL Pipelined MM Bridge" v1.0
# | Altera OpenCL 2011.07.19.13:15:52
# | Pipelined clock crossing splitter
# | 
# | 
# |    ./reset_and_status.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module reset_and_status
# | 
set_module_property DESCRIPTION "Hardware monitoring and software reset logic"
set_module_property NAME reset_and_status
set_module_property VERSION 10.0
set_module_property GROUP "ACL Internal Components"
set_module_property AUTHOR "Altera OpenCL"
set_module_property DISPLAY_NAME "ACL Reset and Status"
set_module_property TOP_LEVEL_HDL_FILE reset_and_status.v
set_module_property TOP_LEVEL_HDL_MODULE reset_and_status
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file reset_and_status.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter PIO_WIDTH INTEGER 32
set_parameter_property PIO_WIDTH DEFAULT_VALUE 32
set_parameter_property PIO_WIDTH DISPLAY_NAME "Pio Width"
set_parameter_property PIO_WIDTH UNITS "bits" 
set_parameter_property PIO_WIDTH AFFECTS_ELABORATION true
set_parameter_property PIO_WIDTH HDL_PARAMETER true

# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk ENABLED true
add_interface_port clk clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk_reset
# | 
add_interface clk_reset reset end
set_interface_property clk_reset associatedClock clk
set_interface_property clk_reset synchronousEdges DEASSERT
set_interface_property clk_reset ENABLED true
add_interface_port clk_reset resetn reset_n Input 1
# | 
# +-----------------------------------


# +-----------------------------------
# | connection point mem0_status
# | 
add_interface mem0_status conduit end
set_interface_property mem0_status ENABLED true
add_interface_port mem0_status mem0_local_init_done local_init_done Input 1
add_interface_port mem0_status mem0_local_cal_success local_cal_success Input 1
add_interface_port mem0_status mem0_local_cal_fail local_cal_fail Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point mem1_status
# | 
add_interface mem1_status conduit end
set_interface_property mem1_status ENABLED true
add_interface_port mem1_status mem1_local_init_done local_init_done Input 1
add_interface_port mem1_status mem1_local_cal_success local_cal_success Input 1
add_interface_port mem1_status mem1_local_cal_fail local_cal_fail Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point lock_kernel_pll
# | 
add_interface lock_kernel_pll conduit end
set_interface_property lock_kernel_pll ENABLED true
add_interface_port lock_kernel_pll lock_kernel_pll export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point fixedclk_locked
# | 
add_interface fixedclk_locked conduit end
set_interface_property fixedclk_locked ENABLED true
add_interface_port fixedclk_locked fixedclk_locked fixedclk_locked Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point mem_organization
# | 
add_interface mem_organization conduit start
set_interface_property mem_organization ENABLED true
add_interface_port mem_organization mem_organization mode Output 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point mem_organization_export
# | 
add_interface mem_organization_export conduit start
set_interface_property mem_organization_export ENABLED true
add_interface_port mem_organization_export mem_organization_export export Output 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point sw_reset
# | 
add_interface sw_reset reset start
set_interface_property sw_reset associatedClock clk
set_interface_property sw_reset synchronousEdges DEASSERT
set_interface_property sw_reset ENABLED true
add_interface_port sw_reset sw_reset_n_out reset_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point pll_reset
# | 
add_interface pll_reset reset start
set_interface_property pll_reset associatedClock clk
set_interface_property pll_reset synchronousEdges DEASSERT
set_interface_property pll_reset ENABLED true
add_interface_port pll_reset pll_reset reset Output 1
# | 
# +-----------------------------------


# +-----------------------------------
# | connection point pio_out
# | 
add_interface pio_out conduit start
set_interface_property pio_out ENABLED true
add_interface_port pio_out pio_out export Input PIO_WIDTH
# | 
# +-----------------------------------


# +-----------------------------------
# | connection point pio_in
# | 
add_interface pio_in conduit end
set_interface_property pio_in ENABLED true
add_interface_port pio_in pio_in export Output PIO_WIDTH
# | 
# +-----------------------------------
