# TCL File Generated by Component Editor 11.0
# Tue Jul 19 13:15:52 PDT 2011


# +-----------------------------------
# | 
# | global_routing_reset "ACL Pipelined MM Bridge" v1.0
# | Altera OpenCL 2011.07.19.13:15:52
# | Pipelined clock crossing splitter
# | 
# | 
# |    ./global_routing_reset.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module global_routing_reset
# | 
set_module_property DESCRIPTION "Hardware monitoring and software reset logic"
set_module_property NAME global_routing_reset
set_module_property VERSION 10.0
set_module_property GROUP "ACL Internal Components"
set_module_property AUTHOR "Altera OpenCL"
set_module_property DISPLAY_NAME "ACL Global Reset Signal"
set_module_property TOP_LEVEL_HDL_FILE global_routing.v
set_module_property TOP_LEVEL_HDL_MODULE global_routing
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file global_routing.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset ENABLED true
set_interface_property reset synchronousEdges NONE
add_interface_port reset s reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point global_reset
# | 
add_interface global_reset reset start
set_interface_property global_reset ENABLED true
set_interface_property global_reset synchronousEdges NONE
add_interface_port global_reset g reset_n Output 1
# | 
# +-----------------------------------
