# TCL File Generated by Component Editor 11.0
# Tue Jul 19 13:15:52 PDT 2011


# +-----------------------------------
# | 
# | mem_org_mode "ACL Pipelined MM Bridge" v1.0
# | Altera OpenCL 2011.07.19.13:15:52
# | Pipelined clock crossing splitter
# | 
# | 
# |    ./mem_org_mode.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module mem_org_mode
# | 
set_module_property DESCRIPTION "Configures address space"
set_module_property NAME mem_org_mode
set_module_property VERSION 10.0
set_module_property GROUP "ACL Internal Components"
set_module_property AUTHOR "Altera OpenCL"
set_module_property DISPLAY_NAME "ACL Mem Organization Control"
set_module_property TOP_LEVEL_HDL_FILE mem_org_mode.v
set_module_property TOP_LEVEL_HDL_MODULE mem_org_mode
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file mem_org_mode.v {SYNTHESIS SIMULATION}
add_file mem_org_mode.sdc {SDC}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter WIDTH INTEGER 32
set_parameter_property WIDTH DEFAULT_VALUE 32
set_parameter_property WIDTH DISPLAY_NAME "Slave Width"
set_parameter_property WIDTH UNITS "bits" 
set_parameter_property WIDTH AFFECTS_ELABORATION true
set_parameter_property WIDTH HDL_PARAMETER true
set_parameter_property WIDTH VISIBLE false

# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk ENABLED true
add_interface_port clk clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk_reset
# | 
add_interface clk_reset reset end
set_interface_property clk_reset associatedClock clk
set_interface_property clk_reset synchronousEdges DEASSERT
set_interface_property clk_reset ENABLED true
add_interface_port clk_reset resetn reset_n Input 1
# | 
# +-----------------------------------


# +-----------------------------------
# | connection point s
# | 
add_interface s avalon end
set_interface_property s addressUnits WORDS
set_interface_property s associatedClock clk
set_interface_property s associatedReset clk_reset
set_interface_property s ENABLED true

add_interface_port s slave_write write Input 1
add_interface_port s slave_writedata writedata Input WIDTH
add_interface_port s slave_read read Input 1
add_interface_port s slave_readdata readdata Output WIDTH
add_interface_port s slave_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point mem_organization_kernel
# | 
add_interface mem_organization_kernel conduit start
set_interface_property mem_organization_kernel ENABLED true
add_interface_port mem_organization_kernel mem_organization_kernel mode Output 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point mem_organization_host
# | 
add_interface mem_organization_host conduit start
set_interface_property mem_organization_host ENABLED true
add_interface_port mem_organization_host mem_organization_host mode Output 2
# | 
# +-----------------------------------
