# TCL File Generated by Component Editor 11.0
# Tue Jul 19 13:15:52 PDT 2011


# +-----------------------------------
# | 
# | clockdiv "ACL Pipelined MM Bridge" v1.0
# | Altera OpenCL 2011.07.19.13:15:52
# | Pipelined clock crossing splitter
# | 
# | 
# |    ./clockdiv.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module clockdiv
# | 
set_module_property DESCRIPTION "Divide clock using soft logic"
set_module_property NAME clockdiv
set_module_property VERSION 10.0
set_module_property GROUP "ACL Internal Components"
set_module_property AUTHOR "Altera OpenCL"
set_module_property DISPLAY_NAME "ACL Clk Divider"
set_module_property TOP_LEVEL_HDL_FILE clockdiv.v
set_module_property TOP_LEVEL_HDL_MODULE clockdiv
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file clockdiv.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter DIV INTEGER 2
set_parameter_property DIV DEFAULT_VALUE 2
set_parameter_property DIV DISPLAY_NAME "Divide value (power of 2)"
set_parameter_property DIV ALLOWED_RANGES {2 4 8 16 32 64 128}
set_parameter_property DIV AFFECTS_ELABORATION true
set_parameter_property DIV HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk ENABLED true
add_interface_port clk clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point div_clk
# | 
add_interface div_clk clock start
set_interface_property div_clk ENABLED true
add_interface_port div_clk div_clk clk Output 1
# | 
# +-----------------------------------
